# -*- coding: utf-8 -*-
"""Week 2 task 2(Control structure)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SUXjQojwfseo_LyZqiP5FkkRdAhSpwEH
"""

grade = 85
if grade>=60:
  print("passed")

grade =85
if grade>=60:
  print("passed")
else:
  print("fail")

result = ('Passed' if grade >= 60 else 'Failed')

print(result)

grade = 77

if grade >= 90:
    print('A')
elif grade >= 80:
    print('B')
elif grade >= 70:
    print('C')
elif grade >= 60:
    print('D')
else:
    print('F')

number = 1

while (number<10):
  print(number, end=" ")
  number+=1

product = 3

while product<=50:
  product = product*3

print(product)

for character in "programming":
  print(character, end=" ")

for counter in range(10):
  print(counter, end=" ")

total = 0
for number in range(1000001):
  total = total+number

print(total)

for number in range(5,10):
  print(number, end=" ")

for number in range(0,10,2):
  print(number, end=" ")

for number in range(10,0,-2):
  print(number, end=" ")

number =  int(input())

for i in range(1,11):
  print(number,"X",i,"=",number*i)

for left in range(7):
    for right in range(left,7):
        print("["+str(left)+"|"+str(right)+"]", end =" ")
    print()

for number in range(10):
  if  number==5:
    break
  print(number, end=" ")

for number in range(10):
  if  number==5:
    continue
  print(number, end=" ")



